# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'kidney_UI.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtWidgets
from PyQt5.QtGui import QIcon
from PyQt5.QtWidgets import QFileDialog, QMessageBox
from calGoods import *


class Ui_KidneyUI(object):
    def setupUi(self, KidneyUI):
        KidneyUI.setObjectName("KidneyUI")
        KidneyUI.resize(350, 236)
        KidneyUI.setWindowIcon(QIcon("logo.ico"))
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(KidneyUI)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label = QtWidgets.QLabel(KidneyUI)
        self.label.setObjectName("label")
        self.verticalLayout_2.addWidget(self.label)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.sourceFilePath = QtWidgets.QLineEdit(KidneyUI)
        self.sourceFilePath.setObjectName("sourceFilePath")
        self.horizontalLayout_2.addWidget(self.sourceFilePath)
        self.sourceFilePathButton = QtWidgets.QPushButton(KidneyUI)
        self.sourceFilePathButton.setObjectName("sourceFilePathButton")
        self.horizontalLayout_2.addWidget(self.sourceFilePathButton)
        self.verticalLayout_2.addLayout(self.horizontalLayout_2)
        self.verticalLayout_3.addLayout(self.verticalLayout_2)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.label_2 = QtWidgets.QLabel(KidneyUI)
        self.label_2.setObjectName("label_2")
        self.verticalLayout.addWidget(self.label_2)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.targetPath = QtWidgets.QLineEdit(KidneyUI)
        self.targetPath.setText("")
        self.targetPath.setObjectName("targetPath")
        self.horizontalLayout.addWidget(self.targetPath)
        self.targetPathButton = QtWidgets.QPushButton(KidneyUI)
        self.targetPathButton.setObjectName("targetPathButton")
        self.horizontalLayout.addWidget(self.targetPathButton)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.verticalLayout_3.addLayout(self.verticalLayout)
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.placeHolder2 = QtWidgets.QLabel(KidneyUI)
        self.placeHolder2.setText("")
        self.placeHolder2.setObjectName("placeHolder2")
        self.gridLayout.addWidget(self.placeHolder2, 3, 2, 1, 1)
        self.stepThreeLabel = QtWidgets.QLabel(KidneyUI)
        self.stepThreeLabel.setObjectName("stepThreeLabel")
        self.gridLayout.addWidget(self.stepThreeLabel, 0, 0, 1, 2)
        self.placeHolder1 = QtWidgets.QLabel(KidneyUI)
        self.placeHolder1.setText("")
        self.placeHolder1.setObjectName("placeHolder1")
        self.gridLayout.addWidget(self.placeHolder1, 3, 0, 1, 1)
        self.confirmButton = QtWidgets.QPushButton(KidneyUI)
        self.confirmButton.setObjectName("confirmButton")
        self.gridLayout.addWidget(self.confirmButton, 3, 1, 1, 1)
        self.readmeLink = QtWidgets.QLabel(KidneyUI)
        self.readmeLink.setOpenExternalLinks(True)
        self.readmeLink.setObjectName("readmeLink")
        self.gridLayout.addWidget(self.readmeLink, 4, 2, 1, 1)
        self.verticalLayout_3.addLayout(self.gridLayout)
        self.verticalLayout_4.addLayout(self.verticalLayout_3)

        self.retranslateUi(KidneyUI)
        QtCore.QMetaObject.connectSlotsByName(KidneyUI)

        try:
            self.sourceFilePathButton.clicked.connect(self.open_event)
        except:
            self.showWarnings()
        try:
            self.targetPathButton.clicked.connect(self.save_event)
        except:
            self.showWarnings()
        try:
            self.confirmButton.clicked.connect(self.make_kidney_table_event)
            self.confirmButton.clicked.connect(self.showMessage)
        except:
            self.showWarnings()

    def open_event(self):
        global path
        _translate = QtCore.QCoreApplication.translate
        directory = QFileDialog.getOpenFileName(None, "选择排表", "./")
        print(directory)  # 打印文件夹路径及filter
        path = directory[0]
        self.sourceFilePath.setText(_translate("Form", path))

    def save_event(self):
        global save_path
        _translate = QtCore.QCoreApplication.translate
        save_path = QFileDialog.getExistingDirectory(None, "肾表保存", "./")
        print(save_path)  # 打印保存文件的全部路径（包括文件名和后缀名）
        self.targetPath.setText(_translate("Form", save_path))

    def make_kidney_table_event(self):
        target_name = path.split("/")[-1]
        target_name = target_name.split(".")[0]
        target_dir = "{}/{}_bill.xlsx".format(save_path, target_name)
        # target_dir = "./test_form_bill.xlsx"
        print(target_dir)
        kidney_maker(path, target_dir)

    def showMessage(self):
        box = QMessageBox()
        box.setWindowTitle("完成")
        box.setWindowIcon(QIcon("logo.ico"))
        box.setText("已生成肾表!")
        continue_ = box.addButton(
            '返回', QtWidgets.QMessageBox.AcceptRole)
        box.setDefaultButton(continue_)
        box.exec_()

    def showWarnings(self):
        box = QMessageBox()
        box.setWindowTitle("错误")
        box.setText("请检查文件输入")
        box.setStandardButtons(QMessageBox.Close)
        reply = box.exec()

    def retranslateUi(self, KidneyUI):
        _translate = QtCore.QCoreApplication.translate
        KidneyUI.setWindowTitle(_translate("KidneyUI", "自动肾表机Demo"))
        self.label.setText(_translate("KidneyUI", "【Step-1】选择排表对应的.xlsx文件"))
        self.sourceFilePath.setPlaceholderText(_translate("KidneyUI", "请选择排表文件"))
        self.sourceFilePathButton.setText(_translate("KidneyUI", "浏览"))
        self.label_2.setText(_translate("KidneyUI", "【Step-2】选择肾表所需保存的路径"))
        self.targetPath.setPlaceholderText(_translate("KidneyUI", "请选择肾表保存路径"))
        self.targetPathButton.setText(_translate("KidneyUI", "浏览"))
        self.stepThreeLabel.setText(_translate("KidneyUI", "【Step-3】点击下方按钮生成肾表"))
        self.confirmButton.setText(_translate("KidneyUI", "生成肾表"))
        self.readmeLink.setText(_translate("KidneyUI",
                                           "<html><head/><body><p><a href=\"https://docs.qq.com/doc/DSVhXS3BST1NQd0tv\"><span style=\" text-decoration: underline; color:#0000ff;\">教程链接</span></a></p></body></html>"))


if __name__ == "__main__":
    import sys

    app = QtWidgets.QApplication(sys.argv)
    KidneyUI = QtWidgets.QWidget()
    ui = Ui_KidneyUI()
    ui.setupUi(KidneyUI)
    KidneyUI.show()
    sys.exit(app.exec_())
